### ISSUE TITLE
Intermittent error

### ISSUE THREAD

**Issue by jameseck** [fiveai/aws-okta#1]
The following error appears intermittently.  It took about 8 tries to get this to appear, but it does happen.

$ aws-okta exec ident-prod-admin -- aws sts get-caller-identity
The collection "awsvault" does not exist. Please add a key first

**Comment by brynmathias** [comment]
additons to this, I often see:
```
➜  privacy_policies git:(ITHD-631-host-streetwise-privacy-policy-as-html-using-s3-and-cloudfront) ✗ aws-okta -t 12h exec market-prd-admin -- terraform plan
The name org.kde.kwalletd was not provided by any .service files
```

This happens on ubuntu with no kde wallet, which I think means that the underlying keychain lib is calling the wrong wallet
